#ifndef ARM64_DECODE_H
#define ARM64_DECODE_H

/*
输入是一条 32 位指令 word，输出是与运行环境无关的结构化语义；
*/

#ifdef __KERNEL__
#include <linux/types.h>
#else
#include <stdint.h>
#endif

#define ARM64_SYSREG_KEY(OP0, OP1, CRN, CRM, OP2) ((((OP0) & 0x3) << 14) | (((OP1) & 0x7) << 11) | (((CRN) & 0xF) << 7) | (((CRM) & 0xF) << 3) | ((OP2) & 0x7))

enum arm64_decode_status
{
    // 指令已完整解码，decoded 中与该 opcode 对应的字段有效。
    ARM64_DECODE_OK,
    // 已识别指令大类，但当前还没有提供完整语义。
    ARM64_DECODE_UNSUPPORTED,
    // 编码已分配，但其行为受架构 constrained-unpredictable 约束。
    ARM64_DECODE_UNPREDICTABLE,
    // 编码属于保留/非法组合，或没有任何子解码器能够识别。
    ARM64_DECODE_UNALLOCATED,
};

// 对应 Arm A64 main encoding table 的顶层指令分类。
enum arm64_insn_class
{
    ARM64_INSN_CLASS_UNKNOWN,
    ARM64_INSN_CLASS_DATA_PROCESSING_IMMEDIATE,
    ARM64_INSN_CLASS_DATA_PROCESSING_REGISTER,
    ARM64_INSN_CLASS_LOAD_STORE,
    ARM64_INSN_CLASS_BRANCH_EXCEPTION_SYSTEM,
    ARM64_INSN_CLASS_DATA_PROCESSING_SIMD_FP,
    ARM64_INSN_CLASS_SVE,
    ARM64_INSN_CLASS_SME,
};

/*
指令编码族/处理路径。opcode 描述指令采用哪种格式，具体运算由 operation
或 operands.simd.operation 表示，例如 ADD/SUB 共用 ADD_SUB 编码族。
*/
enum arm64_opcode
{
    ARM64_OP_UNKNOWN,

    // Branch, exception generation and system instructions.
    ARM64_OP_NOP,
    ARM64_OP_HINT,
    ARM64_OP_BARRIER,
    ARM64_OP_EXCEPTION_GENERATION,
    ARM64_OP_EXCEPTION_RETURN,
    ARM64_OP_MRS,
    ARM64_OP_MSR_REGISTER,
    ARM64_OP_B,
    ARM64_OP_BL,
    ARM64_OP_BR,
    ARM64_OP_BLR,
    ARM64_OP_RET,
    ARM64_OP_B_COND,
    ARM64_OP_CBZ,
    ARM64_OP_CBNZ,
    ARM64_OP_TBZ,
    ARM64_OP_TBNZ,

    // Data processing -- immediate.
    ARM64_OP_ADR,
    ARM64_OP_ADRP,
    ARM64_OP_ADD_SUB_IMMEDIATE,
    ARM64_OP_MIN_MAX_IMMEDIATE,
    ARM64_OP_LOGICAL_IMMEDIATE,
    ARM64_OP_BITFIELD,
    ARM64_OP_EXTRACT,
    ARM64_OP_MOVE_WIDE,
    ARM64_OP_ADD_SUB_SHIFTED,
    ARM64_OP_ADD_SUB_EXTENDED,
    ARM64_OP_LOGICAL_SHIFTED,
    ARM64_OP_CONDITIONAL_SELECT,
    ARM64_OP_DATA_PROCESSING_2_SOURCE,
    ARM64_OP_MULTIPLY_ADD,
    ARM64_OP_MULTIPLY_HIGH,
    ARM64_OP_ADD_SUB_CARRY,
    ARM64_OP_CONDITIONAL_COMPARE,
    ARM64_OP_DATA_PROCESSING_1_SOURCE,

    ARM64_OP_ATOMIC_RMW,
    ARM64_OP_CAS,
    ARM64_OP_CASP,
    ARM64_OP_EXCLUSIVE,
    ARM64_OP_RCPC_UNSCALED,
    ARM64_OP_LDAPR,
    ARM64_OP_PREFETCH,
    ARM64_OP_LOAD_LITERAL,
    ARM64_OP_PREFETCH_LITERAL,
    ARM64_OP_LOAD_STORE_PAIR,
    ARM64_OP_LOAD_STORE_SINGLE,

    ARM64_OP_FP_SIMD,
    ARM64_OP_SVE,
    ARM64_OP_SME,
};

// 常见系统、hint、屏障和异常指令的具体语义。
enum arm64_system_operation
{
    ARM64_SYSTEM_OP_NONE,
    ARM64_SYSTEM_OP_YIELD,
    ARM64_SYSTEM_OP_WFE,
    ARM64_SYSTEM_OP_WFI,
    ARM64_SYSTEM_OP_SEV,
    ARM64_SYSTEM_OP_SEVL,
    ARM64_SYSTEM_OP_CLREX,
    ARM64_SYSTEM_OP_DSB,
    ARM64_SYSTEM_OP_DMB,
    ARM64_SYSTEM_OP_ISB,
    ARM64_SYSTEM_OP_SVC,
    ARM64_SYSTEM_OP_HVC,
    ARM64_SYSTEM_OP_SMC,
    ARM64_SYSTEM_OP_BRK,
    ARM64_SYSTEM_OP_HLT,
    ARM64_SYSTEM_OP_ERET,
    ARM64_SYSTEM_OP_DRPS,
    ARM64_SYSTEM_OP_PACIASP,
    ARM64_SYSTEM_OP_BTI,
};

enum arm64_bti_type
{
    ARM64_BTI_TYPE_NONE = 0,
    ARM64_BTI_TYPE_C = 2,
    ARM64_BTI_TYPE_J = 4,
    ARM64_BTI_TYPE_JC = 6,
};

// 整数、位运算和原子指令的具体语义操作。
enum arm64_operation
{
    ARM64_OPERATION_NONE,
    ARM64_OPERATION_ADD,
    ARM64_OPERATION_SUB,
    ARM64_OPERATION_AND,
    ARM64_OPERATION_ORR,
    ARM64_OPERATION_EOR,
    ARM64_OPERATION_ANDS,
    ARM64_OPERATION_SBFM,
    ARM64_OPERATION_BFM,
    ARM64_OPERATION_UBFM,
    ARM64_OPERATION_EXTR,
    ARM64_OPERATION_MOVN,
    ARM64_OPERATION_MOVZ,
    ARM64_OPERATION_MOVK,
    ARM64_OPERATION_SMAX,
    ARM64_OPERATION_SMIN,
    ARM64_OPERATION_UMAX,
    ARM64_OPERATION_UMIN,
    ARM64_OPERATION_CSEL,
    ARM64_OPERATION_CSINC,
    ARM64_OPERATION_CSINV,
    ARM64_OPERATION_CSNEG,
    ARM64_OPERATION_ADC,
    ARM64_OPERATION_ADCS,
    ARM64_OPERATION_SBC,
    ARM64_OPERATION_SBCS,
    ARM64_OPERATION_CCMP,
    ARM64_OPERATION_CCMN,
    ARM64_OPERATION_UDIV,
    ARM64_OPERATION_SDIV,
    ARM64_OPERATION_LSLV,
    ARM64_OPERATION_LSRV,
    ARM64_OPERATION_ASRV,
    ARM64_OPERATION_RORV,
    ARM64_OPERATION_CRC32B,
    ARM64_OPERATION_CRC32H,
    ARM64_OPERATION_CRC32W,
    ARM64_OPERATION_CRC32X,
    ARM64_OPERATION_CRC32CB,
    ARM64_OPERATION_CRC32CH,
    ARM64_OPERATION_CRC32CW,
    ARM64_OPERATION_CRC32CX,
    ARM64_OPERATION_MADD,
    ARM64_OPERATION_MSUB,
    ARM64_OPERATION_SMADDL,
    ARM64_OPERATION_SMSUBL,
    ARM64_OPERATION_UMADDL,
    ARM64_OPERATION_UMSUBL,
    ARM64_OPERATION_SMULH,
    ARM64_OPERATION_UMULH,
    ARM64_OPERATION_RBIT,
    ARM64_OPERATION_REV16,
    ARM64_OPERATION_REV32,
    ARM64_OPERATION_REV64,
    ARM64_OPERATION_CLZ,
    ARM64_OPERATION_CLS,
    ARM64_OPERATION_CTZ,
    ARM64_OPERATION_CNT,
    ARM64_OPERATION_ABS,
    ARM64_OPERATION_LDADD,
    ARM64_OPERATION_LDCLR,
    ARM64_OPERATION_LDEOR,
    ARM64_OPERATION_LDSET,
    ARM64_OPERATION_LDSMAX,
    ARM64_OPERATION_LDSMIN,
    ARM64_OPERATION_LDUMAX,
    ARM64_OPERATION_LDUMIN,
    ARM64_OPERATION_SWP,
};

// 已归一化的访存寻址模式。
enum arm64_address_mode
{
    ARM64_ADDRESS_NONE,
    ARM64_ADDRESS_LITERAL,
    ARM64_ADDRESS_BASE,
    ARM64_ADDRESS_UNSIGNED_OFFSET,
    ARM64_ADDRESS_UNSCALED_OFFSET,
    ARM64_ADDRESS_PRE_INDEX,
    ARM64_ADDRESS_POST_INDEX,
    ARM64_ADDRESS_REGISTER_OFFSET,
};

// FP/AdvSIMD 的操作数形态；具体动作见 arm64_simd_operation。
enum arm64_simd_form
{
    ARM64_SIMD_FORM_NONE,
    ARM64_SIMD_FORM_SCALAR_FP_IMMEDIATE,
    ARM64_SIMD_FORM_SCALAR_FP_BINARY,
    ARM64_SIMD_FORM_SCALAR_FP_UNARY,
    ARM64_SIMD_FORM_SCALAR_FP_TERNARY,
    ARM64_SIMD_FORM_SCALAR_COMPARE,
    ARM64_SIMD_FORM_SCALAR_CONDITIONAL_COMPARE,
    ARM64_SIMD_FORM_SCALAR_SELECT,
    ARM64_SIMD_FORM_FP_GPR_TRANSFER,
    ARM64_SIMD_FORM_CONVERT,
    ARM64_SIMD_FORM_VECTOR_EXTRACT,
    ARM64_SIMD_FORM_VECTOR_IMMEDIATE,
    ARM64_SIMD_FORM_VECTOR_COPY,
    ARM64_SIMD_FORM_VECTOR_SHIFT,
    ARM64_SIMD_FORM_VECTOR_PERMUTE,
    ARM64_SIMD_FORM_VECTOR_LOGICAL,
    ARM64_SIMD_FORM_VECTOR_INTEGER_3REG,
    ARM64_SIMD_FORM_VECTOR_EXTENDED_3REG,
    ARM64_SIMD_FORM_VECTOR_FP_3REG,
    ARM64_SIMD_FORM_VECTOR_FP_WIDENING_3REG,
    ARM64_SIMD_FORM_VECTOR_COMPLEX_3REG,
    ARM64_SIMD_FORM_VECTOR_FP_UNARY,
    ARM64_SIMD_FORM_VECTOR_REVERSE,
    ARM64_SIMD_FORM_SCALAR_COPY,
    ARM64_SIMD_FORM_FP_BY_ELEMENT,
    ARM64_SIMD_FORM_FP_COMPARE_ZERO,
    ARM64_SIMD_FORM_FP_REDUCE,
    ARM64_SIMD_FORM_SCALAR_SIMD_3REG,
    ARM64_SIMD_FORM_VECTOR_BY_ELEMENT,
    ARM64_SIMD_FORM_SCALAR_BY_ELEMENT,
    ARM64_SIMD_FORM_VECTOR_INTEGER_REDUCE,
    ARM64_SIMD_FORM_VECTOR_NARROW,
    ARM64_SIMD_FORM_SCALAR_NARROW,
};

enum arm64_simd_operation
{
    ARM64_SIMD_OP_NONE,
    ARM64_SIMD_OP_FMUL,
    ARM64_SIMD_OP_FMULX,
    ARM64_SIMD_OP_FDIV,
    ARM64_SIMD_OP_FADD,
    ARM64_SIMD_OP_FSUB,
    ARM64_SIMD_OP_FMAX,
    ARM64_SIMD_OP_FMIN,
    ARM64_SIMD_OP_FMAXNM,
    ARM64_SIMD_OP_FMINNM,
    ARM64_SIMD_OP_FNMUL,
    ARM64_SIMD_OP_FMOV,
    ARM64_SIMD_OP_FABS,
    ARM64_SIMD_OP_FNEG,
    ARM64_SIMD_OP_FSQRT,
    ARM64_SIMD_OP_FRINT,
    ARM64_SIMD_OP_FMLA,
    ARM64_SIMD_OP_FMLS,
    ARM64_SIMD_OP_FMLAL,
    ARM64_SIMD_OP_FMLSL,
    ARM64_SIMD_OP_FMADD,
    ARM64_SIMD_OP_FMSUB,
    ARM64_SIMD_OP_FNMADD,
    ARM64_SIMD_OP_FNMSUB,
    ARM64_SIMD_OP_FADDP,
    ARM64_SIMD_OP_FMAXP,
    ARM64_SIMD_OP_FMINP,
    ARM64_SIMD_OP_FMAXNMP,
    ARM64_SIMD_OP_FMINNMP,
    ARM64_SIMD_OP_FABD,
    ARM64_SIMD_OP_FRECPS,
    ARM64_SIMD_OP_FRSQRTS,
    ARM64_SIMD_OP_FCMP,
    ARM64_SIMD_OP_FCMPE,
    ARM64_SIMD_OP_FCCMP,
    ARM64_SIMD_OP_FCCMPE,
    ARM64_SIMD_OP_FCSEL,
    ARM64_SIMD_OP_FCMEQ,
    ARM64_SIMD_OP_FCMGE,
    ARM64_SIMD_OP_FCMGT,
    ARM64_SIMD_OP_FCMLE,
    ARM64_SIMD_OP_FCMLT,
    ARM64_SIMD_OP_FACGE,
    ARM64_SIMD_OP_FACGT,
    ARM64_SIMD_OP_FAMAX,
    ARM64_SIMD_OP_FAMIN,
    ARM64_SIMD_OP_FSCALE,
    ARM64_SIMD_OP_FCMLA,
    ARM64_SIMD_OP_FCADD,
    ARM64_SIMD_OP_FMAXNMV,
    ARM64_SIMD_OP_FMINNMV,
    ARM64_SIMD_OP_FMAXV,
    ARM64_SIMD_OP_FMINV,
    ARM64_SIMD_OP_FMOV_GENERAL_TO_FP,
    ARM64_SIMD_OP_FMOV_FP_TO_GENERAL,
    ARM64_SIMD_OP_EXT,
    ARM64_SIMD_OP_MOVI,
    ARM64_SIMD_OP_MVNI,
    ARM64_SIMD_OP_ORR,
    ARM64_SIMD_OP_BIC,
    ARM64_SIMD_OP_DUP_GENERAL,
    ARM64_SIMD_OP_DUP_ELEMENT,
    ARM64_SIMD_OP_INS_GENERAL,
    ARM64_SIMD_OP_INS_ELEMENT,
    ARM64_SIMD_OP_UMOV,
    ARM64_SIMD_OP_SMOV,
    ARM64_SIMD_OP_UZP1,
    ARM64_SIMD_OP_TRN1,
    ARM64_SIMD_OP_ZIP1,
    ARM64_SIMD_OP_UZP2,
    ARM64_SIMD_OP_TRN2,
    ARM64_SIMD_OP_ZIP2,
    ARM64_SIMD_OP_AND,
    ARM64_SIMD_OP_ORN,
    ARM64_SIMD_OP_EOR,
    ARM64_SIMD_OP_BSL,
    ARM64_SIMD_OP_BIT,
    ARM64_SIMD_OP_BIF,
    ARM64_SIMD_OP_REV64,
    ARM64_SIMD_OP_REV32,
    ARM64_SIMD_OP_REV16,
    ARM64_SIMD_OP_ADD,
    ARM64_SIMD_OP_SUB,
    ARM64_SIMD_OP_CMEQ,
    ARM64_SIMD_OP_CMGT,
    ARM64_SIMD_OP_CMGE,
    ARM64_SIMD_OP_CMHI,
    ARM64_SIMD_OP_CMHS,
    ARM64_SIMD_OP_SHADD,
    ARM64_SIMD_OP_SQADD,
    ARM64_SIMD_OP_SRHADD,
    ARM64_SIMD_OP_SHSUB,
    ARM64_SIMD_OP_SQSUB,
    ARM64_SIMD_OP_SSHL,
    ARM64_SIMD_OP_SQSHL,
    ARM64_SIMD_OP_SRSHL,
    ARM64_SIMD_OP_SQRSHL,
    ARM64_SIMD_OP_SMAX,
    ARM64_SIMD_OP_SMIN,
    ARM64_SIMD_OP_SABD,
    ARM64_SIMD_OP_SABA,
    ARM64_SIMD_OP_CMTST,
    ARM64_SIMD_OP_MLA,
    ARM64_SIMD_OP_MUL,
    ARM64_SIMD_OP_SMAXP,
    ARM64_SIMD_OP_SMINP,
    ARM64_SIMD_OP_SQDMULH,
    ARM64_SIMD_OP_ADDP,
    ARM64_SIMD_OP_UHADD,
    ARM64_SIMD_OP_UQADD,
    ARM64_SIMD_OP_URHADD,
    ARM64_SIMD_OP_UHSUB,
    ARM64_SIMD_OP_UQSUB,
    ARM64_SIMD_OP_USHL,
    ARM64_SIMD_OP_UQSHL,
    ARM64_SIMD_OP_URSHL,
    ARM64_SIMD_OP_UQRSHL,
    ARM64_SIMD_OP_UMAX,
    ARM64_SIMD_OP_UMIN,
    ARM64_SIMD_OP_UABD,
    ARM64_SIMD_OP_UABA,
    ARM64_SIMD_OP_MLS,
    ARM64_SIMD_OP_PMUL,
    ARM64_SIMD_OP_UMAXP,
    ARM64_SIMD_OP_UMINP,
    ARM64_SIMD_OP_SQRDMULH,
    ARM64_SIMD_OP_SQRDMLAH,
    ARM64_SIMD_OP_SQRDMLSH,
    ARM64_SIMD_OP_SDOT,
    ARM64_SIMD_OP_UDOT,
    ARM64_SIMD_OP_USDOT,
    ARM64_SIMD_OP_SUDOT,
    ARM64_SIMD_OP_BFDOT,
    ARM64_SIMD_OP_BFMLAL,
    ARM64_SIMD_OP_BFMMLA,
    ARM64_SIMD_OP_SMMLA,
    ARM64_SIMD_OP_UMMLA,
    ARM64_SIMD_OP_USMMLA,
    ARM64_SIMD_OP_SHL,
    ARM64_SIMD_OP_SSHR,
    ARM64_SIMD_OP_USHR,

    ARM64_SIMD_OP_SCVTF_S_W,
    ARM64_SIMD_OP_SCVTF_S_X,
    ARM64_SIMD_OP_SCVTF_D_W,
    ARM64_SIMD_OP_SCVTF_D_X,
    ARM64_SIMD_OP_UCVTF_S_W,
    ARM64_SIMD_OP_UCVTF_S_X,
    ARM64_SIMD_OP_UCVTF_D_W,
    ARM64_SIMD_OP_UCVTF_D_X,
    ARM64_SIMD_OP_FCVT_TO_SIGNED,
    ARM64_SIMD_OP_FCVT_TO_UNSIGNED,
    ARM64_SIMD_OP_FCVT_S_D,
    ARM64_SIMD_OP_FCVT_D_S,
    ARM64_SIMD_OP_FCVT_TO_SIGNED_SIMD,
    ARM64_SIMD_OP_FCVT_TO_UNSIGNED_SIMD,
    ARM64_SIMD_OP_SCVTF_SIMD,
    ARM64_SIMD_OP_UCVTF_SIMD,

    ARM64_SIMD_OP_ADDV,
    ARM64_SIMD_OP_SADDLV,
    ARM64_SIMD_OP_UADDLV,
    ARM64_SIMD_OP_SMAXV,
    ARM64_SIMD_OP_SMINV,
    ARM64_SIMD_OP_UMAXV,
    ARM64_SIMD_OP_UMINV,
    ARM64_SIMD_OP_XTN,
    ARM64_SIMD_OP_SQXTN,
    ARM64_SIMD_OP_UQXTN,
    ARM64_SIMD_OP_SQXTUN,
};

enum arm64_fp_rounding_mode
{
    ARM64_FP_ROUND_NONE,
    ARM64_FP_ROUND_NEAREST_EVEN,
    ARM64_FP_ROUND_PLUS_INFINITY,
    ARM64_FP_ROUND_MINUS_INFINITY,
    ARM64_FP_ROUND_ZERO,
    ARM64_FP_ROUND_NEAREST_AWAY,
    ARM64_FP_ROUND_CURRENT,
    ARM64_FP_ROUND_CURRENT_EXACT,
};

enum arm64_simd_rotation
{
    ARM64_SIMD_ROTATION_0,
    ARM64_SIMD_ROTATION_90,
    ARM64_SIMD_ROTATION_180,
    ARM64_SIMD_ROTATION_270,
};

#define ARM64_SIMD_FLAG_COMPARE_ZERO        (1U << 0)
#define ARM64_SIMD_FLAG_SOURCE_HIGH_HALF    (1U << 1)
#define ARM64_SIMD_FLAG_SOURCE_ODD_ELEMENTS (1U << 2)
#define ARM64_SIMD_FLAG_DEST_HIGH_HALF      (1U << 3)

// 跨指令族共享的语义修饰位，调用方无需再检查原始机器码。
#define ARM64_INSN_FLAG_64BIT        (1U << 0)
#define ARM64_INSN_FLAG_SETFLAGS     (1U << 1)
#define ARM64_INSN_FLAG_SUBTRACT     (1U << 2)
#define ARM64_INSN_FLAG_LOAD         (1U << 3)
#define ARM64_INSN_FLAG_STORE        (1U << 4)
#define ARM64_INSN_FLAG_FP           (1U << 5)
#define ARM64_INSN_FLAG_WRITEBACK    (1U << 6)
#define ARM64_INSN_FLAG_SIGN_EXTEND  (1U << 7)
#define ARM64_INSN_FLAG_ACQUIRE      (1U << 8)
#define ARM64_INSN_FLAG_RELEASE      (1U << 9)
#define ARM64_INSN_FLAG_PAIR         (1U << 10)
#define ARM64_INSN_FLAG_INVERT       (1U << 11)
#define ARM64_INSN_FLAG_ORDERED      (1U << 12)
#define ARM64_INSN_FLAG_IMMEDIATE    (1U << 13)
#define ARM64_INSN_FLAG_NON_TEMPORAL (1U << 15)
#define ARM64_INSN_FLAG_UNPRIVILEGED (1U << 16)

struct arm64_branch_operands
{
    // 直接分支的 PC 字节偏移。
    int64_t offset;
    uint8_t condition;
    uint8_t test_bit;
};

struct arm64_pc_relative_operands
{
    // ADR 为 PC 字节偏移，ADRP 为相对当前 PC 页基址的字节偏移。
    int64_t offset;
};

struct arm64_system_operands
{
    enum arm64_system_operation operation;
    // exception immediate 为 imm16；barrier/CLREX 使用低 4 位 option，BTI 使用 arm64_bti_type。
    uint16_t immediate;
    uint8_t option;
    uint8_t op0;
    uint8_t op1;
    uint8_t crn;
    uint8_t crm;
    uint8_t op2;
};

struct arm64_data_operands
{
    // immediate、wmask 和 tmask 已展开为执行器可以直接使用的值。
    uint64_t immediate;
    uint64_t wmask;
    uint64_t tmask;
    uint8_t shift_type;
    uint8_t shift_amount;
    uint8_t option;
    uint8_t immr;
    uint8_t condition;
    uint8_t nzcv;
};

struct arm64_load_store_operands
{
    // offset 始终是字节偏移，access_bytes 是单个元素的访问字节数。
    int64_t offset;
    enum arm64_address_mode address_mode;
    uint8_t access_bytes;
    uint8_t extend_type;
    uint8_t shift_amount;
};

struct arm64_simd_operands
{
    enum arm64_simd_form form;
    enum arm64_simd_operation operation;
    enum arm64_fp_rounding_mode rounding_mode;
    uint64_t expanded_immediate;
    uint32_t flags;
    uint8_t condition;
    uint8_t immediate;
    uint8_t element_width;
    uint8_t result_element_width;
    uint8_t lane_index;
    uint8_t source_lane_index;
};

struct arm64_decoded_insn
{
    // raw/status 使调用方可以缓存单个结构，不必另外保存输入和返回状态。
    uint32_t raw;
    enum arm64_decode_status status;

    // 先按 class 分发，再结合 opcode/operation 解释 union 中的对应成员。
    enum arm64_insn_class insn_class;
    enum arm64_opcode opcode;
    enum arm64_operation operation;
    uint32_t flags;

    // 寄存器字段按编码位置提取；哪些字段具有语义由 opcode 决定。寄存器 31 按原值返回。
    uint8_t rd;
    uint8_t rn;
    uint8_t rm;
    uint8_t ra;
    uint8_t rt;
    uint8_t rt2;
    uint8_t rs;
    // 标量/GPR 指令通常为 32/64；向量指令为有效向量宽度，归约源可为 32/64/128。
    uint8_t operand_width;

    // union 的有效成员由 insn_class/opcode 决定。
    union
    {
        struct arm64_branch_operands branch;
        struct arm64_pc_relative_operands pc_relative;
        struct arm64_system_operands system;
        struct arm64_data_operands data;
        struct arm64_load_store_operands load_store;
        struct arm64_simd_operands simd;
    } operands;
};

/*
解码一条 AArch64 指令。

调用方提供最终结果存储地址，decoder 直接填充该对象，避免大结构体按值返回时
产生隐藏返回槽以及调用端的结构体复制。

输出结构始终包含 raw/status。status 为 OK 时可消费完整语义；为
UNSUPPORTED 时只保证已填写的 class/opcode/flags 等识别信息有效；其他失败
状态下调用方不应执行该指令。
*/
void arm64_decode_insn(uint32_t raw, struct arm64_decoded_insn *decoded);

#endif
